### ISSUE TITLE
Disable for some webs option

### ISSUE THREAD

**Issue by PachiMc** [WofWca/jumpcutter#51] opened 2022-05-13 16:44 UTC
Hi, there should be a whitelist/blacklist for webs because can be bugged in some of them, like twitch

**Comment by WofWca** [comment] 2022-05-13 16:53
Duplicate of #26.
I'm passively working on it (i.e. learning about optional permissions and stuff, trying to find a good way).

**Closed by WofWca** 2022-05-13 16:53 UTC

**Comment by WofWca** [comment] 2022-08-05 12:37
For Twitch there's now this option, which may help

![image](https://user-images.githubusercontent.com/39462442/183078601-4111dc9c-3c99-49d8-b5e3-6c8ebef60f92.png)
